# Generated by Django 5.0.2 on 2024-02-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prowler_app', '0006_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AwsAccount',
        ),
    ]
