# Generated by Django 5.0.2 on 2024-02-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prowler_app', '0008_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awsaccount',
            options={'managed': False},
        ),
    ]
