# Generated by Django 5.0.2 on 2024-02-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prowler_app', '0009_alter_awsaccount_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AwsAccount',
        ),
    ]
