# Generated by Django 5.0.2 on 2024-02-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prowler_app', '0010_delete_awsaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('aws_account_id', models.CharField(max_length=100)),
            ],
        ),
    ]
