# Generated by Django 5.0.2 on 2024-02-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prowler_app', '0013_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AWSModal',
        ),
    ]
