# Generated by Django 5.0.2 on 2024-02-22 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prowler_app', '0016_alter_awsmodal_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='awsmodal',
            unique_together={('user', 'aws_account_id')},
        ),
    ]
